# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSMSN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSMSN

  pod 'Alamofire', '~> 4.5'  
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/Database'

  target 'iOSMSNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSMSNUITests' do
    # Pods for testing
  end

end
